apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- if .Values.secrets }}
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- else }}
{{- end }}
